# docker-compose.prod.yaml
version: "3.9"

services:
    mysql:
        image: "mysql:latest"
        container_name: "mysql-prod"
        ports:
            - 3306:3306
        env_file:
            - ./teaSpot-BE/db/.env
        volumes:
            - db_data:/var/lib/mysql
volumes:
    db_data:
