# docker-compose.prod.yaml
services:
    mysql:
        image: "mysql:latest"
        container_name: "mysql-prod"
        ports:
            - "${MYSQL_PORT:-3306}:3306"
        env_file:
            - ./Be/db/.env
        volumes:
            - db_data:/var/lib/mysql
volumes:
    db_data:
